	tilepal 0, GRAY, GRAY, BROWN, GRAY, GRAY, GRAY, GRAY, BROWN
	tilepal 0, BROWN, ROOF, ROOF, GRAY, GRAY, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, BROWN, GRAY, GRAY, GRAY, GRAY, BROWN
	tilepal 0, BROWN, ROOF, ROOF, GRAY, GRAY, BROWN, BROWN, BROWN
	tilepal 0, ROOF, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, TEXT
