	tilepal 0, GRAY, GREEN, GREEN, GREEN, BROWN, BROWN, GREEN, BROWN
	tilepal 0, BROWN, GRAY, RED, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, BROWN, GREEN, GREEN, GREEN, ROOF, GRAY, GRAY, BROWN
	tilepal 0, BROWN, GRAY, RED, GRAY, GRAY, GRAY, ROOF, ROOF
	tilepal 0, BROWN, BROWN, BROWN, BROWN, ROOF, ROOF, GRAY, GRAY
	tilepal 0, RED, RED, GRAY, GRAY, RED, RED, RED, RED
	tilepal 0, RED, RED, RED, RED, RED, RED, ROOF, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, ROOF
	tilepal 0, GRAY, GRAY
