	tilepal 0, GRAY, YELLOW, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, BROWN, BROWN
	tilepal 0, GREEN, GREEN, BROWN, BROWN, WATER, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GREEN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GRAY, BROWN, BROWN, GRAY, GREEN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, GREEN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, RED, RED, RED, RED
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN
	tilepal 0, GREEN, GREEN
