	object_const_def
	const GAMECORNER_KANTO_BEAUTY1
	const GAMECORNER_KANTO_CLERK1
	const GAMECORNER_POKEFAN_M
	const GAMECORNER_KANTO_BEAUTY2
	const GAMECORNER_FISHING_GURU
	const GAMECORNER_MIDDLE_AGED_WOMAN
	const GAMECORNER_KANTO_GYM_GUIDE
	const GAMECORNER_GAMBLER
	const GAMECORNER_KANTO_CLERK2
	const GAMECORNER_GENTLEMAN
	const GAMECORNER_KANTO_ROCKET

GameCorner_MapScripts:
	def_scene_scripts

	def_callbacks

GameCorner_MapEvents:
	db 0, 0 ; filler

	def_warp_events
	warp_event 15, 17, CELADON_CITY, 8
	warp_event 16, 17, CELADON_CITY, 8
	warp_event 17,  4, ROCKET_HIDEOUT_B1F, 2

	def_coord_events

	def_bg_events
	bg_event  9,  4, BGEVENT_READ, BGEvent

	def_object_events
	object_event  2,  6, SPRITE_KANTO_BEAUTY, SPRITEMOVEDATA_STANDING_DOWN, 0, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, ObjectEvent, -1
	object_event  5,  6, SPRITE_KANTO_CLERK, SPRITEMOVEDATA_STANDING_DOWN, 0, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, ObjectEvent, -1
	object_event  2, 10, SPRITE_POKEFAN_M, SPRITEMOVEDATA_STANDING_LEFT, 0, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, ObjectEvent, -1
	object_event  2, 13, SPRITE_KANTO_BEAUTY, SPRITEMOVEDATA_STANDING_LEFT, 0, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, ObjectEvent, -1
	object_event  5, 11, SPRITE_FISHING_GURU, SPRITEMOVEDATA_STANDING_RIGHT, 0, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, ObjectEvent, -1
	object_event  8, 11, SPRITE_POKEFAN_F, SPRITEMOVEDATA_STANDING_LEFT, 0, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, ObjectEvent, -1
	object_event  8, 14, SPRITE_KANTO_GYM_GUIDE, SPRITEMOVEDATA_STANDING_LEFT, 0, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, ObjectEvent, -1
	object_event 11, 15, SPRITE_GAMBLER, SPRITEMOVEDATA_STANDING_RIGHT, 0, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, ObjectEvent, -1
	object_event 14, 11, SPRITE_KANTO_CLERK, SPRITEMOVEDATA_STANDING_LEFT, 0, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, ObjectEvent, -1
	object_event 17, 13, SPRITE_GENTLEMAN, SPRITEMOVEDATA_STANDING_RIGHT, 0, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, ObjectEvent, -1
	object_event  9,  5, SPRITE_KANTO_ROCKET, SPRITEMOVEDATA_STANDING_UP, 0, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 1, ObjectEvent, -1
