	object_const_def
	const SAFFRONCITY_KANTO_ROCKET1
	const SAFFRONCITY_KANTO_ROCKET2
	const SAFFRONCITY_KANTO_ROCKET3
	const SAFFRONCITY_KANTO_ROCKET4
	const SAFFRONCITY_KANTO_ROCKET5
	const SAFFRONCITY_KANTO_ROCKET6
	const SAFFRONCITY_KANTO_ROCKET7
	const SAFFRONCITY_KANTO_SCIENTIST
	const SAFFRONCITY_SILPH_WORKER
	const SAFFRONCITY_KANTO_ERIKA
	const SAFFRONCITY_GENTLEMAN
	const SAFFRONCITY_KANTO_BIRD
	const SAFFRONCITY_KANTO_ROCKER
	const SAFFRONCITY_KANTO_ROCKET8
	const SAFFRONCITY_KANTO_ROCKET9

SaffronCity_MapScripts:
	def_scene_scripts

	def_callbacks
	callback MAPCALLBACK_NEWMAP, .FlyPoint

.FlyPoint:
	setflag ENGINE_FLYPOINT_SAFFRON
	endcallback

SaffronCity_MapEvents:
	def_warp_events
	warp_event  7,  5, COPYCATS_HOUSE_1F, 1
	warp_event 26,  3, FIGHTING_DOJO, 1
	warp_event 34,  3, SAFFRON_GYM, 1
	warp_event 13, 11, SAFFRON_PIDGEY_HOUSE, 1
	warp_event 25, 11, SAFFRON_MART, 1
	warp_event 18, 21, SILPH_CO_1F, 1
	warp_event  9, 29, SAFFRON_POKECENTER, 1
	warp_event 29, 29, MR_PSYCHICS_HOUSE, 1

	def_coord_events

	def_bg_events
	bg_event 17,  5, BGEVENT_READ, BGEvent
	bg_event 27,  5, BGEVENT_READ, BGEvent
	bg_event 35,  5, BGEVENT_READ, BGEvent
	bg_event 26, 11, BGEVENT_READ, BGEvent
	bg_event 39, 19, BGEVENT_READ, BGEvent
	bg_event  5, 21, BGEVENT_READ, BGEvent
	bg_event 15, 21, BGEVENT_READ, BGEvent
	bg_event 10, 29, BGEVENT_READ, BGEvent
	bg_event 27, 29, BGEVENT_READ, BGEvent
	bg_event  1, 19, BGEVENT_READ, BGEvent

	def_object_events
	object_event  7,  6, SPRITE_KANTO_ROCKET, SPRITEMOVEDATA_SPINRANDOM_SLOW, 0, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, ObjectEvent, -1
	object_event 20,  8, SPRITE_KANTO_ROCKET, SPRITEMOVEDATA_WALK_LEFT_RIGHT, 4, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, ObjectEvent, -1
	object_event 34,  4, SPRITE_KANTO_ROCKET, SPRITEMOVEDATA_SPINRANDOM_SLOW, 0, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, ObjectEvent, -1
	object_event 13, 12, SPRITE_KANTO_ROCKET, SPRITEMOVEDATA_SPINRANDOM_SLOW, 0, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, ObjectEvent, -1
	object_event 11, 25, SPRITE_KANTO_ROCKET, SPRITEMOVEDATA_WALK_LEFT_RIGHT, 4, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, ObjectEvent, -1
	object_event 32, 13, SPRITE_KANTO_ROCKET, SPRITEMOVEDATA_WALK_LEFT_RIGHT, 4, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, ObjectEvent, -1
	object_event 18, 30, SPRITE_KANTO_ROCKET, SPRITEMOVEDATA_WALK_LEFT_RIGHT, 4, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, ObjectEvent, -1
	object_event  8, 14, SPRITE_KANTO_SCIENTIST, SPRITEMOVEDATA_WANDER, 4, 4, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, ObjectEvent, -1
	object_event 23, 23, SPRITE_SILPH_WORKER, SPRITEMOVEDATA_SPINRANDOM_SLOW, 0, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, ObjectEvent, -1
	object_event 17, 30, SPRITE_KANTO_ERIKA, SPRITEMOVEDATA_WALK_LEFT_RIGHT, 4, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, ObjectEvent, -1
	object_event 30, 12, SPRITE_GENTLEMAN, SPRITEMOVEDATA_STANDING_DOWN, 0, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, ObjectEvent, -1
	object_event 31, 12, SPRITE_KANTO_BIRD, SPRITEMOVEDATA_STANDING_DOWN, 0, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, ObjectEvent, -1
	object_event 18,  8, SPRITE_KANTO_ROCKER, SPRITEMOVEDATA_STANDING_UP, 0, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, ObjectEvent, -1
	object_event 18, 22, SPRITE_KANTO_ROCKET, SPRITEMOVEDATA_STANDING_DOWN, 0, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, ObjectEvent, -1
	object_event 19, 22, SPRITE_KANTO_ROCKET, SPRITEMOVEDATA_STANDING_DOWN, 0, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, ObjectEvent, -1
